easy_admin:
    site_name: 'Skeleton'
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        User:
            class: App\Entity\User
